import Head from "next/head";

import styles from "../styles/Home.module.css";
import { AiFillInstagram, AiFillFacebook } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/deved.webp";
import design from '../public/design.png'
import code from '../public/code.png'
import idk from '../public/consulting.png'
import { useState } from "react";
import { useTheme } from "next-themes";
import { BsMoonFill, BsFillSunFill } from "react-icons/bs";
import { useEffect } from "react";
 function Home() {
 
  return (
    <div >
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="   px-5   md:px-20 lg:px-40 ">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-semibold ">USAID Tech</h1>
            <ul className="flex items-center">
              <li className=" cursor-pointer text-1xl ">
              <ThemeChanger />
              </li>
              <li>
                <a
                  href="#"
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
              Ali Usaid
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl ">full stack developer </h3>
            <p className=" text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white ">
              “This field requires patience, and the ability to troubleshoot and
              get at errors. You need to be a learning worker, have the
              motivation to learn on your own,Join me down below and lets get Cracking
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.instagram.com/maybe_not_ali/"><AiFillInstagram /></a>
            <a href="https://www.facebook.com/ali.usaid75/"><AiFillFacebook /></a>
          </div>
          <div className=" relative bg-gradient-to-r from-cyan-500 to-teal-500 rounded-full w-80 h-80 mx-auto mt-20 overflow-hidden md:w-96 md:h-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 mt-10 ">
             services  i Offer 
            </h3>
            <p className=" py-2 text-md leading-8 text-gray-800 dark:text-white">
              Since the start of my Journey as a freelancer Developer, i have done remote  work for
           <span className="text-teal-500"> Clients </span> and work with some talented <span>People</span> as well to create digital products for both business and consumer use
            </p>
            <p className=" py-2 text-md leading-8 text-gray-800 dark:text-white">
              I offer wide range of Services including programming, Responsive design
            </p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-r from-cyan-500 to-teal-500">
              <Image src={design} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-900">Beautiful Design</h3>
              <p className="py-2 dark:text-gray-900">Creating beautiful and Responsive design according to your design theory </p>
              <h4 className="py-4 text-teal-600 text-3xl dark:text-gray-900"> Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-900">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-gray-900 ">Material UI</p>
              <p className="text-gray-800 py-1 dark:text-gray-900">bootstrap</p>

            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-r from-cyan-500 to-teal-500">
              <Image src={code} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-900">full stack developer </h3>
              <p className="py-2 dark:text-gray-900">Lets, Code your dream project ! ,, You have idea for your project well lets make it a reality</p>
              <h4 className="py-4 text-teal-600 text-3xl dark:text-gray-900">Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-900">React Js</p>
              <p className="text-gray-800 py-1 dark:text-gray-900">Next Js</p>
              <p className="text-gray-800 py-1 dark:text-gray-900">Firebase / Node Js</p>

            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-r from-cyan-500 to-teal-500">
              <Image src={idk} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-900">Need Advice</h3>
              <p className="py-2 dark:text-gray-900">Need help with your Project i can give you some tricks to level it up :-) </p>
            
           

            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
export default Home;

const ThemeChanger = () => {
  const  {Theme, setTheme}= useTheme()
  const [Mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
  
  
  }, [])
  if(!Mounted) {
    return null;
  }
  return(
    <div>
    
      <BsFillSunFill onClick={() => setTheme('light')} className='text-white'/>
      <BsMoonFill onClick={() => setTheme('dark')} className='text-gray-900'/>

    
    </div>
  )
}